version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_login
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3001:3001'
    command: npm run start:prod
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mariadb_data:
